/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct entrada {
	int arg1;
	int arg2;
};
typedef struct entrada entrada;

#define CAL 0x30000001
#define UNO 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  int * suma_1(entrada *, CLIENT *);
extern  int * suma_1_svc(entrada *, struct svc_req *);
#define resta 2
extern  int * resta_1(entrada *, CLIENT *);
extern  int * resta_1_svc(entrada *, struct svc_req *);
#define multi 3
extern  int * multi_1(entrada *, CLIENT *);
extern  int * multi_1_svc(entrada *, struct svc_req *);
#define div 4
extern  int * div_1(entrada *, CLIENT *);
extern  int * div_1_svc(entrada *, struct svc_req *);
extern int cal_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define resta 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define multi 3
extern  int * multi_1();
extern  int * multi_1_svc();
#define div 4
extern  int * div_1();
extern  int * div_1_svc();
extern int cal_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entrada (XDR *, entrada*);

#else /* K&R C */
extern bool_t xdr_entrada ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
